/* Copyright (c) 2006, Stefan Eilemann <eile@equalizergraphics.com> 
   All rights reserved. */

#ifndef EQ_CONFIGEVENT_H
#define EQ_CONFIGEVENT_H

#include <eq/client/packets.h>

namespace eq
{
    /** 
     * A config event.
     *
     * Config events are generated by the event processing functions on the
     * render nodes and send to the config thread, i.e., to the application
     * using Config::sendEvent(). The config processes events at the end of the
     * frame, either non-blocking or blocking (event-driven). Config events are
     * typically application-specific. The events defined below are for the
     * default implementation, which sends the window system events more or less
     * unprocessed to the application.
     *
     * When subclassing, make sure to set the packet size.
     */
    struct ConfigEvent : public ConfigPacket
    {
    public:
        enum Type
        {
            TYPE_MOUSE_MOTION,
            TYPE_MOUSE_BUTTON_PRESS,
            TYPE_MOUSE_BUTTON_RELEASE,
            TYPE_KEY_PRESS,
            TYPE_KEY_RELEASE
        };

        ConfigEvent()
            {
                command = CMD_CONFIG_EVENT;
                size    = sizeof( ConfigEvent );
            }

        Type type;

        union // event data: Move into subclass?
        {
            struct
            {
                int x; // relative to screen
                int y;
                int w;
                int h;
            } resize;

            struct
            {
                int x; // relative to config
                int y;
                // TODO button id
            } mouseMotion, mouseButtonPress, mouseButtonRelease;

            struct
            {
                unsigned key; // atm config-system native key code
            } keyPress, keyRelease;
        };
    };

    std::ostream& operator << ( std::ostream& os, const ConfigEvent* event );
}

#endif // EQ_CONFIGEVENT_H

