
/* Copyright (c) 2006-2009, Stefan Eilemann <eile@equalizergraphics.com> 
   All rights reserved. */

#ifndef EQ_CONFIGEVENT_H
#define EQ_CONFIGEVENT_H

#include <eq/client/event.h>   // member
#include <eq/client/packets.h> // base class

namespace eq
{
    /** 
     * A config event.
     *
     * Config events are generated by the event processing functions on the
     * render nodes and send to the config thread, i.e., to the application
     * using Config::sendEvent(). The config processes events at the end of the
     * frame, either non-blocking or blocking (event-driven). Config events are
     * typically application-specific. The events defined below are for the
     * default implementation, which sends the window system events more or less
     * unprocessed to the application.
     *
     * When subclassing, make sure to set the packet size.
     */
    struct EQ_EXPORT ConfigEvent : public ConfigPacket
    {
    public:
        ConfigEvent()
            {
                command = CMD_CONFIG_EVENT;
                size    = sizeof( ConfigEvent );
            }
        
        Event data;
    };

    EQ_EXPORT std::ostream& operator << ( std::ostream& os, 
                                          const ConfigEvent* event );
}

#endif // EQ_CONFIGEVENT_H

