
include $(TOP)/make/system.mk

MODULE = eqCompressorRLE

CXXFILES = \
	compressor.cpp \
	compressorRLE.cpp \
	compressorRLE4B.cpp \
	compressorRLE4U.cpp \
	compressorRLE4HF.cpp

TARGETS = $(DYNAMIC_LIB)

include $(TOP)/make/rules.mk
