
include $(TOP)/make/system.mk

MODULE = eqCompressorRLE

CXXFILES = \
	compressor.cpp \
	compressorRLE.cpp \
	compressorRLE4B.cpp \
#	compressorRLE3B.cpp \
#	compressorRLE4F.cpp \
#	compressorRLE4HF.cpp \
#	compressorRLEByte.cpp

TARGETS = $(DYNAMIC_LIB)

include $(TOP)/make/rules.mk
