
Equalizer is built using CMake, preferably using Buildyard[1]. For a
optional and required dependencies refer to the graph on the Buildyard
page. Optional packaged, e.g., hwloc, will generate a harmless warning
when running CMake. Please report any issues to the eq-dev mailing list.

Tested are:
 * building and installing on Ubuntu, Mac OS X and Windows
 * creating binary package for Ubuntu
 * creating binary installer for Windows (with selectable components!)
 * creating binary installer for Mac OS X

[1] https://github.com/Eyescale/Buildyard
