typedef union{
    const char*             _string;
    int                     _int;
    unsigned                _unsigned;
    float                   _float;
    eqNet::ConnectionType   _connectionType;
    float                   _viewport[4];
} YYSTYPE;
#define	EQTOKEN_GLOBAL	258
#define	EQTOKEN_CONNECTION_SATTR_HOSTNAME	259
#define	EQTOKEN_CONNECTION_SATTR_LAUNCH_COMMAND	260
#define	EQTOKEN_CONNECTION_IATTR_TYPE	261
#define	EQTOKEN_CONNECTION_IATTR_TCPIP_PORT	262
#define	EQTOKEN_CONNECTION_IATTR_LAUNCH_TIMEOUT	263
#define	EQTOKEN_CONFIG_FATTR_EYE_BASE	264
#define	EQTOKEN_WINDOW_IATTR_HINT_STEREO	265
#define	EQTOKEN_WINDOW_IATTR_HINT_DOUBLEBUFFER	266
#define	EQTOKEN_WINDOW_IATTR_HINT_FULLSCREEN	267
#define	EQTOKEN_WINDOW_IATTR_HINT_DECORATION	268
#define	EQTOKEN_WINDOW_IATTR_PLANES_COLOR	269
#define	EQTOKEN_WINDOW_IATTR_PLANES_ALPHA	270
#define	EQTOKEN_WINDOW_IATTR_PLANES_DEPTH	271
#define	EQTOKEN_WINDOW_IATTR_PLANES_STENCIL	272
#define	EQTOKEN_CHANNEL_IATTR_HINT_STATISTICS	273
#define	EQTOKEN_SERVER	274
#define	EQTOKEN_CONFIG	275
#define	EQTOKEN_APPNODE	276
#define	EQTOKEN_NODE	277
#define	EQTOKEN_PIPE	278
#define	EQTOKEN_WINDOW	279
#define	EQTOKEN_ATTRIBUTES	280
#define	EQTOKEN_HINT_STEREO	281
#define	EQTOKEN_HINT_DOUBLEBUFFER	282
#define	EQTOKEN_HINT_FULLSCREEN	283
#define	EQTOKEN_HINT_DECORATION	284
#define	EQTOKEN_HINT_STATISTICS	285
#define	EQTOKEN_PLANES_COLOR	286
#define	EQTOKEN_PLANES_ALPHA	287
#define	EQTOKEN_PLANES_DEPTH	288
#define	EQTOKEN_PLANES_STENCIL	289
#define	EQTOKEN_ON	290
#define	EQTOKEN_OFF	291
#define	EQTOKEN_AUTO	292
#define	EQTOKEN_FASTEST	293
#define	EQTOKEN_NICEST	294
#define	EQTOKEN_CHANNEL	295
#define	EQTOKEN_COMPOUND	296
#define	EQTOKEN_CONNECTION	297
#define	EQTOKEN_NAME	298
#define	EQTOKEN_TYPE	299
#define	EQTOKEN_TCPIP	300
#define	EQTOKEN_HOSTNAME	301
#define	EQTOKEN_COMMAND	302
#define	EQTOKEN_TIMEOUT	303
#define	EQTOKEN_TASK	304
#define	EQTOKEN_EYE	305
#define	EQTOKEN_EYE_BASE	306
#define	EQTOKEN_BUFFER	307
#define	EQTOKEN_CLEAR	308
#define	EQTOKEN_DRAW	309
#define	EQTOKEN_ASSEMBLE	310
#define	EQTOKEN_READBACK	311
#define	EQTOKEN_COLOR	312
#define	EQTOKEN_DEPTH	313
#define	EQTOKEN_CYCLOP	314
#define	EQTOKEN_LEFT	315
#define	EQTOKEN_RIGHT	316
#define	EQTOKEN_VIEWPORT	317
#define	EQTOKEN_RANGE	318
#define	EQTOKEN_DISPLAY	319
#define	EQTOKEN_SCREEN	320
#define	EQTOKEN_WALL	321
#define	EQTOKEN_BOTTOM_LEFT	322
#define	EQTOKEN_BOTTOM_RIGHT	323
#define	EQTOKEN_TOP_LEFT	324
#define	EQTOKEN_SYNC	325
#define	EQTOKEN_LATENCY	326
#define	EQTOKEN_SWAPBARRIER	327
#define	EQTOKEN_OUTPUTFRAME	328
#define	EQTOKEN_INPUTFRAME	329
#define	EQTOKEN_STRING	330
#define	EQTOKEN_FLOAT	331
#define	EQTOKEN_INTEGER	332
#define	EQTOKEN_UNSIGNED	333


extern YYSTYPE eqLoader_lval;
