
include $(TOP)/make/system.mk

OPTIONAL = \
	$(wildcard WorldSkin) \
	$(wildcard god)

SUBDIRS = \
	configs \
	eqHello \
	eqPly \
	eqPixelBench \
	eVolve \
	$(OPTIONAL)

TARGETS = subdirs

include $(TOP)/make/rules.mk
