
include $(TOP)/make/system.mk

MODULE = base

SOURCES = \
	barrier.cpp \
	idPool.cpp \
	lock.cpp \
	log.cpp \
	requestHandler.cpp \
	thread.cpp \
	timedLock.cpp

all: $(HEADERS) $(STATIC_LIB)

include $(TOP)/make/rules.mk
