
# Copyright (c) 2011-2013 Stefan Eilemann <eile@eyescale.ch>

if(APPLE)
  # WAR otherwise MacPorts X11 (/opt/local) is preferred
  list(REMOVE_ITEM CMAKE_SYSTEM_LIBRARY_PATH /opt/local/lib)
  list(REMOVE_ITEM CMAKE_SYSTEM_PREFIX_PATH /opt/local)
  link_directories(/opt/X11/lib /usr/X11R6/lib)
  include_directories(SYSTEM /opt/X11/include /usr/X11R6/include)
endif()

common_package(Boost REQUIRED COMPONENTS program_options filesystem system thread)
common_package(Collage REQUIRED)
common_package(Deflect)
common_package(GLStats)
common_package(hwloc)
common_package(hwsd)
common_package(Lunchbox REQUIRED)
common_package(MAGELLAN)
common_package(OpenCV)
common_package(OpenGL REQUIRED)
common_package(OpenSceneGraph COMPONENTS osgDB osgUtil)
common_package(Pression REQUIRED)
common_package(Qt5Core)
common_package(Qt5Gui)
common_package(Qt5Widgets)
common_package(vmmlib REQUIRED)
common_package(VRPN)
common_package(X11 SYSTEM)
if(APPLE) # tweak window systems before finding glew
  if(EQ_AGL_USED)
    set(X11_FOUND)
  else()
    if(EQUALIZER_PREFER_QT AND Qt5Gui_FOUND)
      set(X11_FOUND)
    elseif(X11_FOUND)
      set(Qt5Gui_FOUND)
    endif()
  endif()
endif()
common_package(GLEW_MX)
common_package_post()

if(APPLE)
  LIST(APPEND CMAKE_SYSTEM_LIBRARY_PATH /opt/local/lib)
  LIST(APPEND CMAKE_SYSTEM_PREFIX_PATH /opt/local)
endif(APPLE)

if(CUDA_FOUND)
  set(CUDA_PROPAGATE_HOST_FLAGS OFF)
endif(CUDA_FOUND)
