# Copyright (c) 2010 Daniel Pfeifer <daniel@pfeifer-mail.de>
#               2010 Stefan Eilemann <eile@eyescale.ch>

set(EQ_FABRIC_FORWARD_HEADERS
    api.h
    base.h
    canvas.h
    canvasPackets.h
    channel.h
    colorMask.h
    commands.h
    config.h
    configPackets.h
    configVisitor.h
    client.h
    drawableConfig.h
    elementVisitor.h
    eye.h
    error.h
    frustum.h
    global.h
    layout.h
    layoutPackets.h
    iAttribute.h
    init.h
    leafVisitor.h
    log.h
    node.h
    nodeType.h
    object.h
    observer.h
    packets.h
    packetType.h
    paths.h
    pipe.h
    pipePackets.h
    pixel.h
    pixelViewport.h
    projection.h
    range.h
    renderContext.h
    segment.h
    serializable.h
    server.h
    serverPackets.h
    subPixel.h
    task.h
    types.h
    viewport.h
    view.h
    visitorResult.h
    wall.h
    window.h
    windowPackets.h
    zoom.h
  )

set(EQ_FABRIC_HEADERS
   nameFinder.h
  )

set(EQ_FABRIC_SOURCES
    canvas.ipp
    channel.ipp
    client.cpp
    colorMask.cpp
    config.ipp
    eye.cpp
    frustum.cpp
    global.cpp
    iAttribute.cpp
    init.cpp
    layout.ipp
    node.ipp
    object.cpp
    observer.ipp
    pixel.cpp
    pipe.ipp
    projection.cpp
    range.cpp
    renderContext.cpp
    segment.ipp
    server.ipp
    subPixel.cpp
    view.ipp
    viewport.cpp
    window.ipp
    wall.cpp
    zoom.cpp
  )

