##
# Path : libs/collage/files.cmake
# Copyright (c) 2010 Cedric Stalder <cedric.stalder@gmail.ch>
#               2011-2012 Stefan Eilemann <eile@eyescale.ch>
##

set(COBASE_PUBLIC_HEADERS 
    base/api.h
    base/atomic.h
    base/base.h
    base/bitOperation.h
    base/buffer.h
    base/clock.h
    base/compiler.h
    base/condition.h
    base/debug.h
    base/defines.h
    base/dso.h
    base/error.h
    base/errorRegistry.h
    base/file.h
    base/global.h
    base/hash.h
    base/init.h
    base/launcher.h
    base/lfQueue.h
    base/lock.h
    base/lockable.h
    base/log.h
    base/memoryMap.h
    base/monitor.h
    base/mtQueue.h
    base/nonCopyable.h
    base/omp.h
    base/os.h
    base/perThread.h
    base/perThreadRef.h
    base/pluginRegistry.h
    base/pool.h
    base/refPtr.h
    base/referenced.h
    base/requestHandler.h
    base/rng.h
    base/scopedMutex.h
    base/sleep.h
    base/spinLock.h
    base/stdExt.h
    base/thread.h
    base/threadID.h
    base/timedLock.h
    base/types.h
    base/uint128_t.h
    base/uuid.h
  )

set(COBASE_HEADERS 
    base/compressor.h
    base/compressorInfo.h
    base/cpuCompressor.h
    base/memcpy.h
    base/plugin.h
  )

 set(COBASE_SOURCES
    base/atomic.cpp
    base/clock.cpp
    base/compressor.cpp
    base/condition.cpp
    base/condition_w32.ipp
    base/cpuCompressor.cpp
    base/debug.cpp
    base/dso.cpp
    base/error.cpp
    base/errorRegistry.cpp
    base/file.cpp
    base/global.cpp
    base/init.cpp
    base/launcher.cpp
    base/lock.cpp
    base/log.cpp
    base/memoryMap.cpp
    base/omp.cpp
    base/plugin.cpp
    base/pluginRegistry.cpp
    base/referenced.cpp
    base/requestHandler.cpp
    base/rng.cpp
    base/spinLock.cpp
    base/sleep.cpp
    base/thread.cpp
    base/threadID.cpp
    base/timedLock.cpp
    base/uint128_t.cpp
    base/uuid.cpp
  )
