
/* Copyright (c) 2011, Fatih Erol
 *
 */

#ifndef MASS_VOL__GUI_CONNECTION_DEFS_H
#define MASS_VOL__GUI_CONNECTION_DEFS_H


#define VOL_VIS_GUI_DEFAULT_HOST "127.0.0.1"
#define VOL_VIS_GUI_DEFAULT_PORT 4999

#define VOL_VIS_GUI_MAX_PATH_LEN 1024

#endif  // MASS_VOL__GUI_CONNECTION_DEFS_H


